version: '3.3'

services:
  app:
    container_name: myfirst_dockerized_rest_server
    build:
      dockerfile: rest_api/Dockerfile
      context: .
    volumes:
      - ./rest_api:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
  
  db:
    image: mysql
    container_name: myfirst_dockerized_database_server
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_dumps/world.sql:/docker-entrypoint-initdb.d/world.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
